import { it, expect } from 'vitest';
import { spawn, type ChildProcess } from 'node:child_process';
import { once } from 'node:events';
import { readFileSync } from 'node:fs';
import { superviseTrustedHost } from '../src/trusted-host-supervision.js';
import { qualificationProcessIdentity, qualificationProcessMatches, type QualificationProcessIdentity } from '../src/qualification-process.js';
const child=async(code:string,detached=true)=>{const p=spawn(process.execPath,['-e',`process.on('message',()=>{${code}})`],{detached,env:{},stdio:['ignore','pipe','pipe','ipc']});await once(p,'spawn');return p;};
const options=()=>({wallMs:2000,settlementMs:1000,maxOutputBytes:1024,signal:new AbortController().signal});
async function clean(p:ChildProcess){if(p.exitCode===null&&p.signalCode===null){p.kill('SIGKILL');await once(p,'exit');}}
it('observes owned success without retaining output or claiming acceptance',async()=>{const p=await child("process.stdout.write('private-fixture-text');process.exit(0)");try{const done=superviseTrustedHost(p,options());p.send('go');const r=await done;expect(r).toMatchObject({outcome:'completed',exitCode:0,acceptance:'not-assessed',stdoutBytes:20});expect(JSON.stringify(r)).not.toContain('private-fixture-text');}finally{await clean(p);}});
it('times out a blocked child event loop independently, even if TERM is ignored',async()=>{const p=await child("process.on('SIGTERM',()=>{});process.send('ready');while(true){}"),o=options();o.wallMs=500;try{const done=superviseTrustedHost(p,o);p.send('go');await once(p,'message');const r=await done;expect(r.outcome).toBe('timed-out');expect(r.signal).toBe('SIGKILL');}finally{await clean(p);}});
it('forwards original cancellation without changing a timeout into success',async()=>{const p=await child("process.send('ready');setInterval(()=>{},1000)"),controller=new AbortController();try{const done=superviseTrustedHost(p,{...options(),signal:controller.signal});p.send('go');await once(p,'message');controller.abort();expect((await done).outcome).toBe('aborted');}finally{await clean(p);}});
it('stops at a combined stdout/stderr byte bound',async()=>{const p=await child("process.stdout.write('x'.repeat(600));process.stderr.write('y'.repeat(600));setInterval(()=>{},1000)");try{const done=superviseTrustedHost(p,options());p.send('go');const r=await done;expect(r.outcome).toBe('output-limit');expect(r.stdoutBytes+r.stderrBytes).toBeGreaterThan(1024);expect(r.truncated).toBe(true);}finally{await clean(p);}});
it('refuses duplicate monitoring of the same original child',async()=>{const p=await child('process.exit(0)');try{const done=superviseTrustedHost(p,options());await expect(superviseTrustedHost(p,options())).rejects.toThrow('already monitored');p.send('go');expect((await done).outcome).toBe('completed');}finally{await clean(p);}});
it('retains a failed exit rather than blessing absence of a model error',async()=>{const p=await child('process.exit(7)');try{const done=superviseTrustedHost(p,options());p.send('go');expect(await done).toMatchObject({outcome:'failed',exitCode:7});}finally{await clean(p);}});
it('refuses an inherited unrelated process group without signalling the caller',async()=>{const p=await child('setInterval(()=>{},1000)',false);try{await expect(superviseTrustedHost(p,options())).rejects.toThrow('detached');expect(p.exitCode).toBe(null);}finally{await clean(p);}});
it('rejects invalid limits without terminating a process it did not accept',async()=>{const p=await child('setInterval(()=>{},1000)');try{await expect(superviseTrustedHost(p,{...options(),wallMs:0})).rejects.toThrow('limits');expect(p.exitCode).toBe(null);}finally{await clean(p);}});
it('reports unknown when an escaped group holds pipes, rather than claiming containment',async()=>{const p=await child("const c=require('child_process').spawn(process.execPath,['-e','setInterval(()=>{},1000)'],{detached:true,stdio:['ignore','inherit','inherit']});c.on('spawn',()=>{process.send(c.pid);setTimeout(()=>process.exit(0),20);});");let identity:QualificationProcessIdentity|null=null;try{const done=superviseTrustedHost(p,{...options(),settlementMs:200});p.send('go');const [pid]=await once(p,'message');identity=qualificationProcessIdentity(pid);expect((await done).outcome).toBe('unknown');expect(qualificationProcessMatches(identity)).toBe(true);}finally{if(identity&&qualificationProcessMatches(identity)){try{process.kill(identity.pid,'SIGKILL');}catch{}}await clean(p);}});
it('cleans same-group descendants after the leader exits',async()=>{const p=await child("const c=require('child_process').spawn(process.execPath,['-e','setInterval(()=>{},1000)'],{stdio:['ignore','inherit','inherit']});c.on('spawn',()=>{process.send(c.pid);setTimeout(()=>process.exit(0),20);});");let pid=0,identity:QualificationProcessIdentity|null=null;try{const done=superviseTrustedHost(p,options());p.send('go');[pid]=await once(p,'message');identity=qualificationProcessIdentity(pid);expect((await done).outcome).toBe('completed');let state='gone';try{const s=readFileSync('/proc/'+pid+'/stat','utf8');state=s.slice(s.lastIndexOf(')')+2).split(' ')[0];}catch{}expect(['gone','Z','X']).toContain(state);}finally{await clean(p);if(identity&&qualificationProcessMatches(identity)){try{process.kill(identity.pid,'SIGKILL');}catch{}}}});
