// Run only in the documented no-home, network-unshared fixture namespace.
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
globalThis.fetch=async()=>{throw Error('real fetch disabled');};globalThis.WebSocket=class {constructor(){throw Error('WebSocket disabled');}};
const {stream}=await import('/sdk/node_modules/@earendil-works/pi-ai/dist/api/openai-codex-responses.js');
const catalogue=JSON.parse(readFileSync('/sdk/node_modules/@earendil-works/pi-ai/dist/providers/data/openai-codex.json','utf8'))['openai-codex-responses'];
const {executeCodexQualification,codexCharterHash}=await import('/harness/packages/adapters/dist/codex-subscription.js');
const {openLocalCodexHost}=await import('/harness/packages/adapters/dist/codex-host-observer.js');
const sha=s=>createHash('sha256').update(s).digest('hex');
const models=['gpt-5.4','gpt-5.6-sol','gpt-5.5','gpt-5.3-codex-spark','gpt-5.4-mini'];
function charter(){return {version:'codex-synthetic-charter-v1',provider:'openai-codex',destination:'https://chatgpt.com/backend-api/codex/responses',rolePolicy:models.map((model,i)=>({role:i===0?'proposer':i===1?'subject':'judge',model,canonical:'fixture-'+i,lineage:'shared-fixture'})),identityEvidence:{kind:'fixture',reference:'synthetic-only'},hostEvidence:{kind:'fixture',reference:'synthetic-only'},accountId:'fixture-no-account',runtime:{sdkRoot:'/sdk',oauthFile:'/no-auth-mount',fingerprints:{}},serverOutputTokenCap:null,limits:{calls:5,requestBytes:4096,responseBytes:16384,totalRequestBytes:20480,totalResponseBytes:81920,callMs:30000,wallMs:150000},invocations:models.map((model,i)=>({id:['proposer','subject','first','second','tie'][i],role:i===0?'proposer':i===1?'subject':'judge',model,effort:'low',instructions:i<2?'Return only the integer.':'Return JSON verdict and suspect.',input:i<2?'What is 2 + 2?':'Must equal 4.',expectedSha256:sha('4'),subjectId:i>1?'subject':null}))};}
function sse(model,text){const item={id:'msg_'+model,type:'message',role:'assistant',status:'completed',content:[{type:'output_text',text,annotations:[]}]};return [{type:'response.created',response:{id:'resp_'+model,status:'in_progress'}},{type:'response.output_item.added',output_index:0,item:{...item,status:'in_progress',content:[]}},{type:'response.output_text.delta',output_index:0,content_index:0,item_id:item.id,delta:text},{type:'response.output_item.done',output_index:0,item},{type:'response.completed',response:{id:'resp_'+model,model,status:'completed',output:[item],usage:{input_tokens:1,output_tokens:1,total_tokens:2}}}].map((e,i)=>`data: ${JSON.stringify({...e,sequence_number:i})}\n\n`).join('');}
let passed=0;
for(const scenario of ['success','split','alias','unknown','stale-policy','destination','no-approval','wrong-owner','live-fixtures','api-key','credential-failure','quota','auth','redirect','oversize','budget','deadline','retry','wire-destination']) {
 const c=charter(),path='/out/'+scenario;let reads=0,sends=0,cancelled=0;
 if(scenario==='alias')c.rolePolicy[1].canonical=c.rolePolicy[0].canonical;if(scenario==='unknown')c.rolePolicy[1].canonical=null;if(scenario==='destination')c.destination='https://example.invalid/';if(scenario==='budget')c.limits.totalResponseBytes=32768;if(scenario==='deadline')c.limits.callMs=200;
 const a={scope:'fixture',charterSha256:codexCharterHash(c),approvalId:'fixture-only',expiresAt:Date.now()+60000,journalPath:path};
 if(scenario==='stale-policy')c.rolePolicy[1].lineage='changed';if(scenario==='wrong-owner')a.journalPath='/out/other';if(scenario==='live-fixtures')a.scope='subscription-live';
 const credential={type:'oauth',provider:'openai-codex',accountId:'fixture-no-account',expires:Date.now()+60000,access:'fixture.'+Buffer.from(JSON.stringify({'https://api.openai.com/auth':{chatgpt_account_id:'fixture-no-account'}})).toString('base64url')+'.invalid'};
 const bindings=Object.fromEntries(models.map(model=>[model,{model:catalogue[model],stream:scenario==='retry'?(m,c,o)=>stream(m,c,{...o,fetch:async(...args)=>{await o.fetch(...args);return o.fetch(...args);}}):scenario==='wire-destination'?(m,c,o)=>stream(m,c,{...o,fetch:(_url,init)=>o.fetch('https://example.invalid/',init)}):stream}]));
 const ports={bindings,credentials:{kind:'fixture-oauth',read:async()=>{reads++;if(scenario==='api-key')return {type:'api_key',key:'!must-never-resolve'};if(scenario==='credential-failure')throw Error('DO_NOT_RETAIN_CREDENTIAL_DETAIL');return credential;}},transport:{kind:'fixture-http',exchange:async(wire,_credential,signal)=>{sends++;assert.equal(wire.destination,c.destination);assert.equal(wire.method,'POST');assert.ok(wire.body.length<=c.limits.requestBytes);if(scenario==='deadline')return new Response(new ReadableStream({cancel(){cancelled++;}}),{headers:{'content-type':'text/event-stream'}});if(['quota','auth','redirect'].includes(scenario))return new Response('{}',{status:{quota:429,auth:401,redirect:302}[scenario]});if(scenario==='oversize')return new Response('x'.repeat(16385),{headers:{'content-type':'text/event-stream'}});const model=models[sends-1],text=sends<=2?'4':JSON.stringify({verdict:scenario==='split'&&sends===4?'FAIL':'PASS',suspect:false});return new Response(sse(model,text),{headers:{'content-type':'text/event-stream'}});}}};
 const run=()=>executeCodexQualification(path,c,scenario==='no-approval'?undefined:a,ports);
 if(['success','split'].includes(scenario)){const result=await run();assert.equal(result.executionMode,'fixture');assert.equal(result.liveQualified,false);assert.equal(result.panel.collapse.verdict,'PASS');assert.equal(sends,scenario==='split'?5:4);await run();assert.equal(sends,scenario==='split'?5:4);}
 else {await assert.rejects(run);if(existsSync(path)){const count=openLocalCodexHost(path).inspect().calls;assert.equal(count,scenario==='budget'?2:1);const before=reads;await assert.rejects(run);assert.equal(reads,before);const log=readFileSync(path+'/events.jsonl','utf8');assert.ok(!log.includes(credential.access)&&!log.includes('DO_NOT_RETAIN_CREDENTIAL_DETAIL'));}else assert.equal(reads+sends,0);}
 if(['alias','unknown','stale-policy','destination','no-approval','wrong-owner','live-fixtures'].includes(scenario))assert.equal(reads+sends,0);
 if(['api-key','credential-failure','wire-destination'].includes(scenario))assert.equal(sends,0);
 if(scenario==='budget')assert.equal(reads,2);if(scenario==='deadline')assert.equal(cancelled,1);
 passed++;console.log(JSON.stringify({scenario,fixtureCredentialReads:reads,fixtureHttpCalls:sends,realCredentialReads:0,liveCalls:0,passed:true}));
}
console.log(JSON.stringify({passed,realCredentialReads:0,liveCalls:0,qualification:false}));
