import { expect,it } from 'vitest';
import { inertCodexSdkStreams } from '../src/codex-sdk-transport.js';
const model={id:'gpt-6-astra',provider:'openai-codex',api:'openai-codex-responses',baseUrl:'https://chatgpt.com/backend-api'};
const request={model:model.id,instructions:'Integer only',input:[{role:'user',content:[{type:'input_text',text:'2 + 2'}]}],reasoning:{effort:'low'},parallel_tool_calls:false};
function body(){const item={id:'synthetic-item',type:'message',role:'assistant',status:'completed',content:[{type:'output_text',text:'4'}]};return [{type:'response.created',response:{id:'synthetic-response',status:'in_progress'}},{type:'response.output_item.added',output_index:0,item:{...item,status:'in_progress',content:[]}},{type:'response.output_text.delta',output_index:0,content_index:0,item_id:item.id,delta:'4'},{type:'response.output_item.done',output_index:0,item},{type:'response.completed',response:{id:'synthetic-response',model:model.id,status:'completed',output:[item]}}].map((e,sequence_number)=>'data: '+JSON.stringify({...e,sequence_number})+'\n\n').join('');}
it('retains distinct closed response failure categories, preserves original errors and leaves success unchanged',async()=>{
 for(const scenario of ['success','missing','empty','missing-invalid','missing-wrongmodel','missing-truncated','missing-201','other','sse','record','diagnostic-recorder-fails']){
  const records:any[]=[],original=Error('synthetic initiating recorder error'),secondary=Error('synthetic secondary recorder error');let calls=0,decoderType:string|null=null,originalReply:Response|undefined;const missing=scenario.startsWith('missing')||scenario==='empty',success=['success','missing','empty'].includes(scenario);
  const stream=(_m:any,_c:any,o:any)=>({result:async()=>{o.onPayload(request);const reply=await o.fetch('https://chatgpt.com/backend-api/codex/responses',{method:'POST',body:JSON.stringify(request)});decoderType=reply.headers.get('content-type');return {model:model.id,provider:model.provider,api:model.api,stopReason:'stop',content:[{type:'text',text:'4'}]};}});
  const ports=inertCodexSdkStreams({model,stream},async()=>{calls++;let payload=['sse','missing-invalid'].includes(scenario)?'synthetic malformed SSE':body();if(scenario==='missing-wrongmodel')payload=payload.replaceAll('gpt-6-astra','wrong-model');if(scenario==='missing-truncated')payload=payload.slice(0,-1);originalReply=new Response(Buffer.from(payload),{status:scenario==='missing-201'?201:200,headers:scenario==='empty'?{'content-type':''}:missing?{}:{'content-type':scenario==='other'?'application/x-synthetic-private-header':'text/event-stream'}});return originalReply;},r=>{if(r.type==='sdk-response-validated'&&['record','diagnostic-recorder-fails'].includes(scenario))throw original;if(r.type==='sdk-response-failed'&&scenario==='diagnostic-recorder-fails')throw secondary;records.push(r);});
  const chunks:Buffer[]=[];const done=new Promise<void>((resolve,reject)=>{ports.response.on('data',b=>chunks.push(b));ports.response.once('end',resolve);ports.response.once('error',reject);ports.transport.once('error',reject);});ports.transport.end(JSON.stringify(request));
  try{if(success){await done;expect(decoderType).toBe('text/event-stream');expect(originalReply!.headers.get('content-type')).toBe(scenario==='empty'?'':missing?null:'text/event-stream');if(missing)expect(records.find(r=>r.type==='sdk-response-validated')).toMatchObject({originalMediaType:'missing',decoderMediaType:'event-stream',mediaTypeDerived:true});expect(Buffer.concat(chunks).toString()).toBe('4');expect(records.some(r=>r.type==='sdk-response-failed')).toBe(false);expect(records.some(r=>r.type==='sdk-decoded')).toBe(true);}else{const error=await done.then(()=>null,e=>e);expect(error).toBeInstanceOf(Error);if(['record','diagnostic-recorder-fails'].includes(scenario))expect(error).toBe(original);expect(records.some(r=>r.type==='sdk-decoded')).toBe(false);if(scenario!=='diagnostic-recorder-fails')expect(records.find(r=>r.type==='sdk-response-failed')).toEqual({type:'sdk-response-failed',category:['sse','missing-invalid','missing-wrongmodel','missing-truncated'].includes(scenario)?'SSE-validation-failed':scenario==='record'?'validation-record-failed':'media-type-invalid',mediaType:missing?'missing':scenario==='other'?'other':'event-stream',liveQualified:false});}expect(calls).toBe(1);}finally{ports.transport.destroy();ports.response.destroy();}
 }
});
