import { expect, it } from 'vitest';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { Readable, Writable } from 'node:stream';
import { createHash } from 'node:crypto';
import { createLocalCodexHost } from '../src/codex-host-observer.js';
import { startCodexProducerIpc } from '../src/codex-producer-ipc.js';
const sha=(s:string)=>createHash('sha256').update(s).digest('hex');
const deferred=()=>{let resolve!:()=>void;return {promise:new Promise<void>(r=>resolve=r),resolve:()=>resolve()};};
function world(withJudge=false){
 const path=join(mkdtempSync(join(tmpdir(),'codex-producer-')),'host'),model='gpt-5.6-sol',charterSha256='a'.repeat(64);
 const binding={version:'producer-ipc-v1',budgetDigest:'b'.repeat(64),orderId:'order',experimentId:'experiment',executionId:'execution-fixture',charterSha256,invocationId:'subject'};
 const host=createLocalCodexHost(path,{version:'codex-host-local-v1',maxCalls:2,wallMs:10000,invocations:[{id:'subject',role:'subject',model,effort:'low',instructions:'Integer only',input:'2+2',expectedSha256:sha('4'),subjectId:null},...(withJudge?[{id:'judge',role:'judge' as const,model:'gpt-5.5',effort:'low' as const,instructions:'Judge',input:'Integer4',expectedSha256:sha('4'),subjectId:'subject'}]:[])]},[{role:'proposer',model:'gpt-5.4',canonical:'p',lineage:'shared'},{role:'subject',model,canonical:'s',lineage:'shared'},{role:'judge',model:'gpt-5.5',canonical:'j',lineage:'shared'}],{charterSha256,mode:'fixture',requestBytes:4096,responseBytes:16384,totalRequestBytes:20480,totalResponseBytes:81920,callMs:10000});
 let starts=0,writes=0;const held=deferred(),exchanged=deferred();let terminal='completed';
 const producer={createProducerIpcHost:(i:any)=>i,startProducerIpc:async(i:any)=>{starts++;const completion=i.host.exchange(Readable.from([JSON.stringify({id:'subject',sequence:1})+'\n']),{binding,signal:i.signal}).then(async(references:any)=>{exchanged.resolve();await held.promise;return {binding,outcome:terminal,settlement:'acknowledged',childState:'settled',hostState:'acknowledged',frameSha256:sha(JSON.stringify({id:'subject',sequence:1})+'\n'),acceptance:'not-assessed',references};});return {completion,result:completion,inspect:()=>({outcome:'pending'})};}};
 const sdk={model:{id:model,provider:'openai-codex',api:'openai-codex-responses',baseUrl:'https://chatgpt.com/backend-api'},stream:(_m:any,c:any,o:any)=>({result:async()=>{const body=o.onPayload({model,store:false,stream:true,instructions:c.systemPrompt,input:[{role:'user',content:[{type:'input_text',text:c.messages[0].content}]}],text:{verbosity:'low'},include:['reasoning.encrypted_content'],tool_choice:'none',reasoning:{effort:'low',summary:'auto'}});await o.fetch('https://chatgpt.com/backend-api/codex/responses',{method:'POST',body:JSON.stringify(body)});return {model,provider:'openai-codex',api:'openai-codex-responses',stopReason:'stop',content:[{type:'text',text:'4'}]};}})};
 const item={id:'item',type:'message',role:'assistant',status:'completed',content:[{type:'output_text',text:'4'}]};
 const events=[{type:'response.created',response:{id:'response',status:'in_progress'}},{type:'response.output_item.added',output_index:0,item:{...item,status:'in_progress',content:[]}},{type:'response.output_text.delta',output_index:0,content_index:0,item_id:'item',delta:'4'},{type:'response.output_item.done',output_index:0,item},{type:'response.completed',response:{id:'response',model,status:'completed',output:[item]}}];
 const transport={kind:'fixture-http' as const,exchange:async()=>{writes++;return new Response(events.map((e,sequence_number)=>'data: '+JSON.stringify({...e,sequence_number})+'\n\n').join(''),{headers:{'content-type':'text/event-stream'}});}};
 const input={path,binding,sdk,transport,producer,owner:{},permit:{},signal:new AbortController().signal,timeoutMs:10000};
 return {input,host,held,exchanged,counts:()=>({starts,writes}),fail:()=>terminal='failed'};
}
it('refuses a different charter before constructing/starting a producer or sending bytes',async()=>{const w=world();await expect(startCodexProducerIpc({...w.input,binding:{...w.input.binding,charterSha256:'c'.repeat(64)}})).rejects.toThrow();expect(w.counts()).toEqual({starts:0,writes:0});});
it('holds host eligibility until original producer completion acknowledges, then retains real host references',async()=>{const w=world(),run=await startCodexProducerIpc(w.input);await w.exchanged.promise;expect(w.host.eligibleOutputs()).toEqual([]);expect(w.host.inspect().complete).toBe(false);w.held.resolve();const done=await run.completion;expect(done.outcome).toBe('completed');expect(w.host.eligibleOutputs()).toHaveLength(1);expect(w.host.inspect().complete).toBe(true);expect(w.counts()).toEqual({starts:1,writes:1});await expect(startCodexProducerIpc(w.input)).rejects.toThrow();expect(w.counts()).toEqual({starts:1,writes:1});});
it('blocks judge bytes while a successful subject source still lacks original settlement',async()=>{const w=world(true),run=await startCodexProducerIpc(w.input);await w.exchanged.promise;let writes=0;try{await expect(w.host.exchange(Readable.from(['{"id":"judge","sequence":1}\n']),new Writable({write(_b,_e,cb){writes++;cb();}}),Readable.from(['{"verdict":"PASS","suspect":false}']),true)).rejects.toThrow('source unsettled');expect(writes).toBe(0);expect(w.host.inspect().calls).toBe(1);}finally{w.held.resolve();await run.completion;}});
it('rejects fabricated completed references instead of making a completed ownership claim',async()=>{const w=world(),start=w.input.producer.startProducerIpc;w.input.producer.startProducerIpc=async i=>{const run=await start(i);return {...run,completion:run.completion.then(r=>({...r,references:{claimRef:'fabricated',responseRef:'fabricated'}}))};};const run=await startCodexProducerIpc(w.input);w.held.resolve();await expect(run.completion).rejects.toThrow('completion mismatch');expect(w.host.eligibleOutputs()).toEqual([]);});
it('does not turn a successful host response into eligible evidence when producer settlement fails',async()=>{const w=world();w.fail();const run=await startCodexProducerIpc(w.input);await w.exchanged.promise;w.held.resolve();await run.completion;expect(w.host.eligibleOutputs()).toEqual([]);expect(w.host.inspect()).toMatchObject({aborted:true,complete:false});});
