import { it, expect } from 'vitest';
import { mkdtempSync, existsSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import { codexCharterHash, executeCodexQualification, createReadOnlyCodexOAuthPort, createCodexOAuthFilePort } from '../src/codex-subscription.js';
const sha=(s:string)=>createHash('sha256').update(s).digest('hex');
export function charter():any {const models=['gpt-5.4','gpt-5.6-sol','gpt-5.5','gpt-5.3-codex-spark','gpt-5.4-mini'];return {version:'codex-synthetic-charter-v1',destination:'https://chatgpt.com/backend-api/codex/responses',provider:'openai-codex',rolePolicy:models.map((model,i)=>({role:i===0?'proposer':i===1?'subject':'judge',model,canonical:'fixture-'+i,lineage:'shared-fixture'})),identityEvidence:{kind:'fixture',reference:'synthetic-only'},hostEvidence:{kind:'fixture',reference:'synthetic-only'},accountId:'fixture-no-account',runtime:{sdkRoot:'/fixture-sdk',oauthFile:'/fixture-auth',fingerprints:{}},limits:{calls:5,requestBytes:4096,responseBytes:16384,totalRequestBytes:20480,totalResponseBytes:81920,callMs:30000,wallMs:150000},invocations:models.map((model,i)=>({id:['proposer','subject','first','second','tie'][i],role:i===0?'proposer':i===1?'subject':'judge',model,effort:'low',instructions:i<2?'Return only the integer.':'Return JSON verdict and suspect.',input:i<2?'What is 2 + 2?':'Must equal 4.',expectedSha256:sha('4'),subjectId:i>1?'subject':null})),serverOutputTokenCap:null};}
const approval=(c:any)=>({scope:'fixture',charterSha256:codexCharterHash(c),approvalId:'test-only',expiresAt:Date.now()+60000,journalPath:'/unbound'});
it('rejects missing/changed charters, canonical policies, destinations and aggregate budgets before credential/transport effects',async()=>{
 for(const change of ['missing','destination','alias','unknown','budget','policy','expired','live-fixture']) {const c=charter(),a:any=approval(c);let effects=0;const p=join(mkdtempSync(join(tmpdir(),'codex-preflight-')),'owner');a.journalPath=p;
  const bindings=Object.fromEntries(c.invocations.map((i:any)=>[i.model,{model:{id:i.model,provider:'openai-codex',api:'openai-codex-responses',baseUrl:'https://chatgpt.com/backend-api'},stream:()=>{effects++;throw Error('must not invoke SDK');}}]));
  if(change==='destination')c.destination='https://example.invalid/';if(change==='alias')c.rolePolicy[1].canonical=c.rolePolicy[0].canonical;if(change==='unknown')c.rolePolicy[1].canonical=null;if(change==='budget')c.limits.totalResponseBytes=1;if(change==='policy')c.rolePolicy[1].lineage='changed';if(change==='expired')a.expiresAt=0;if(change==='live-fixture')a.scope='subscription-live';
  await expect(executeCodexQualification(p,c,change==='missing'?undefined:a,{bindings,credentials:{kind:'fixture-oauth',read:async()=>{effects++;throw Error('must not read');}},transport:{kind:'fixture-http',exchange:async()=>{effects++;throw Error('must not send');}}})).rejects.toThrow();expect(effects).toBe(0);expect(existsSync(p)).toBe(false);
 }
});
it('refuses API-key storage entries without reading/resolving their helper',async()=>{let reads=0;const port=createReadOnlyCodexOAuthPort(()=>({list:async()=>[{providerId:'openai-codex',type:'api_key'}],read:async()=>{reads++;return {type:'api_key',key:'!forbidden-helper'};}}));await expect(port.read(new AbortController().signal)).rejects.toThrow('oauth-credential-unavailable');expect(reads).toBe(0);});
it('reads only a bounded synthetic OAuth file and never returns its refresh field',async()=>{const path=join(mkdtempSync(join(tmpdir(),'codex-auth-fixture-')),'auth.json');const access='fixture.'+Buffer.from(JSON.stringify({'https://api.openai.com/auth':{chatgpt_account_id:'fixture-no-account'}})).toString('base64url')+'.invalid';writeFileSync(path,JSON.stringify({'openai-codex':{type:'oauth',access,refresh:'fake-refresh-must-not-return',expires:Date.now()+1000}}),{mode:0o600});const result:any=await createCodexOAuthFilePort(path).read(new AbortController().signal);expect(result.type).toBe('oauth');expect(result.accountId).toBe('fixture-no-account');expect(result.refresh).toBeUndefined();});
it('sanitizes credential storage failures rather than exposing raw errors',async()=>{const port=createReadOnlyCodexOAuthPort(()=>{throw Error('sensitive fixture detail');});await expect(port.read(new AbortController().signal)).rejects.toThrow(/^oauth-credential-unavailable$/);});
