import {expect,it} from 'vitest';
import {validateCodexTextSse,inertCodexSdkStreams} from '../src/codex-sdk-transport.js';
function events(summary='synthetic summary'):any[]{const rid='synthetic-reasoning',mid='synthetic-answer',part={type:'summary_text',text:summary},reason={id:rid,type:'reasoning',content:[],summary:summary==='none'?[]:[part],encrypted_content:'opaque-final'},text={type:'output_text',text:'4'},message={id:mid,type:'message',role:'assistant',phase:'final_answer',status:'completed',content:[text]};return [
 {type:'response.created',response:{id:'synthetic-response',status:'in_progress'}},
 {type:'response.output_item.added',output_index:0,item:{...reason,summary:[],encrypted_content:'opaque-initial'}},
 ...(summary==='none'?[]:[{type:'response.reasoning_summary_part.added',output_index:0,item_id:rid,summary_index:0,part:{...part,text:''}},{type:'response.reasoning_summary_text.delta',output_index:0,item_id:rid,summary_index:0,delta:summary},{type:'response.reasoning_summary_text.done',output_index:0,item_id:rid,summary_index:0,text:summary},{type:'response.reasoning_summary_part.done',output_index:0,item_id:rid,summary_index:0,part}]),
 {type:'response.output_item.done',output_index:0,item:reason},
 {type:'response.output_item.added',output_index:1,item:{...message,status:'in_progress',content:[]}},
 {type:'response.content_part.added',output_index:1,item_id:mid,content_index:0,part:{...text,text:''}},
 {type:'response.output_text.delta',output_index:1,item_id:mid,content_index:0,delta:'4'},
 {type:'response.output_text.done',output_index:1,item_id:mid,content_index:0,text:'4'},
 {type:'response.content_part.done',output_index:1,item_id:mid,content_index:0,part:text},
 {type:'response.output_item.done',output_index:1,item:message},
 {type:'response.completed',response:{id:'synthetic-response',model:'gpt-5.5',status:'completed',output:[]}},
 ];}
const bytes=(e:any[])=>Buffer.from(e.map((v,sequence_number)=>'data: '+JSON.stringify({...v,sequence_number})+'\n\n').join(''));
it.each(['synthetic summary','none',''])('accepts bounded optional summary %# without exposing it',s=>{const e=events(s);expect(validateCodexTextSse(bytes(e),'gpt-5.5')).toEqual({text:'4',responseId:'synthetic-response'});e.at(-1).response.output=e.filter(v=>v.type==='response.output_item.done').map(v=>v.item);expect(validateCodexTextSse(bytes(e),'gpt-5.5').text).toBe('4');});
it.each(['cross-item','index','summary-index','wrong-summary','duplicate','reorder','unfinished','reasoning-only','tool','wrong-model','truncated','unknown','cipher-size','summary-size','changed-final','extra-text','same-id','private-content'])('rejects reasoning %s',change=>{const e=events(),find=(type:string)=>e.find(x=>x.type===type);if(change==='cross-item')find('response.reasoning_summary_text.delta').item_id='other';if(change==='index')find('response.reasoning_summary_text.delta').output_index=1;if(change==='summary-index')find('response.reasoning_summary_part.done').summary_index=1;if(change==='wrong-summary')find('response.reasoning_summary_text.done').text='other';if(change==='duplicate')e.splice(2,0,structuredClone(e[1]));if(change==='reorder')[e[3],e[4]]=[e[4],e[3]];if(change==='unfinished')e.splice(e.findIndex(x=>x.type==='response.output_item.done'),1);if(change==='reasoning-only')e.splice(7,e.length-8);if(change==='tool')e[1].item.type='function_call';if(change==='wrong-model')e.at(-1).response.model='wrong';if(change==='unknown')e[3].type='response.unknown';if(change==='cipher-size')e[1].item.encrypted_content='x'.repeat(8193);if(change==='summary-size')find('response.reasoning_summary_text.delta').delta='x'.repeat(4097);if(change==='changed-final')e.at(-1).response.output=[e.at(-2).item];if(change==='extra-text')e.splice(e.length-1,0,structuredClone(e.at(-2)));if(change==='same-id')e[7].item.id=e[1].item.id;if(change==='private-content')e[1].item.content=[{type:'reasoning_text',text:'synthetic'}];const b=bytes(e);expect(()=>validateCodexTextSse(change==='truncated'?b.subarray(0,-1):b,'gpt-5.5')).toThrow();});
it.each(['valid','none','empty','text','signature','missing-thinking','extra-thinking','response-id'])('SDK %s correlates thinking privately and emits final text only',async change=>{const e=events(change==='none'?'none':change==='empty'?'':'synthetic summary'),reason=e.find(v=>v.type==='response.output_item.done').item,model={id:'gpt-5.5',provider:'openai-codex',api:'openai-codex-responses',baseUrl:'https://chatgpt.com/backend-api'},request={model:model.id,instructions:'Integer only',input:[{role:'user',content:[{type:'input_text',text:'2+2'}]}],reasoning:{effort:'low'},parallel_tool_calls:false};const content:any[]=[{type:'thinking',thinking:change==='none'?'':change==='empty'?'\n\n':'synthetic summary',thinkingSignature:JSON.stringify(reason)},{type:'text',text:'4'}];if(change==='text')content[0].thinking='other';if(change==='signature')content[0].thinkingSignature=JSON.stringify({...reason,encrypted_content:'wrong'});if(change==='missing-thinking')content.shift();if(change==='extra-thinking')content.unshift(structuredClone(content[0]));const records:any[]=[];const stream=(_m:any,_c:any,o:any)=>({result:async()=>{o.onPayload(request);await o.fetch('https://chatgpt.com/backend-api/codex/responses',{method:'POST',body:JSON.stringify(request)});return {model:model.id,provider:model.provider,api:model.api,responseId:change==='response-id'?'wrong':'synthetic-response',stopReason:'stop',content};}});const ports=inertCodexSdkStreams({model,stream},async()=>new Response(bytes(e)),r=>records.push(r));const chunks:Buffer[]=[];const done=new Promise<void>((resolve,reject)=>{ports.response.on('data',b=>chunks.push(b));ports.response.once('end',resolve);ports.response.once('error',reject);ports.transport.once('error',reject);});ports.transport.end(JSON.stringify(request));try{if(['valid','none','empty'].includes(change)){await done;expect(Buffer.concat(chunks).toString()).toBe('4');const safe=records.filter(r=>r.type!=='sdk-response-observed'&&r.type!=='sdk-wire-observed');expect(JSON.stringify(safe)).not.toContain('synthetic summary');expect(JSON.stringify(safe)).not.toContain('opaque-final');}else await expect(done).rejects.toThrow();}finally{ports.transport.destroy();ports.response.destroy();}});
