import { it, expect } from 'vitest';
import { loadCodexDiagnosticModel } from '../src/codex-diagnostic-model.js';
import { mkdtempSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { Readable } from 'node:stream';
import { createHash } from 'node:crypto';
import { executeProducerCodexQualification, executeProducerCodexSingleRequest, executeCodexQualification, codexCharterHash } from '../src/codex-subscription.js';
import { learningJournal } from '../src/learning-journal.js';
const sha=(v:string)=>createHash('sha256').update(v).digest('hex');
const deferred=()=>{let resolve!:()=>void;return {promise:new Promise<void>(r=>resolve=r),resolve:()=>resolve()};};
function world(scenario='normal',proposer='gpt-5.4') {
 const path=join(mkdtempSync(join(tmpdir(),'codex-five-')),'owner'),ids=['proposer','subject','first','second','tie'],models=[proposer,'gpt-5.6-sol','gpt-5.5','gpt-5.3-codex-spark','gpt-5.4-mini'];
 const c:any={version:'codex-synthetic-charter-v1',provider:'openai-codex',destination:'https://chatgpt.com/backend-api/codex/responses',rolePolicy:models.map((model,k)=>({model,role:k===0?'proposer':k===1?'subject':'judge',canonical:'fixture-'+k,lineage:'shared-fixture'})),identityEvidence:{kind:'fixture',reference:'inert'},hostEvidence:{kind:'fixture',reference:'inert'},accountId:'fixture-account',serverOutputTokenCap:null,runtime:{sdkRoot:'/fixture-sdk',oauthFile:'/fixture-auth',fingerprints:{}},limits:{calls:5,requestBytes:4096,responseBytes:16384,totalRequestBytes:20480,totalResponseBytes:81920,callMs:10000,wallMs:60000},invocations:models.map((model,k)=>({id:ids[k],model,role:k===0?'proposer':k===1?'subject':'judge',effort:'low',instructions:k<2?'Integer only':'JSON verdict only',input:k<2?'2+2':'Must equal 4',expectedSha256:sha('4'),subjectId:k<2?null:'subject'}))};
 const approval:any={scope:'fixture',charterSha256:codexCharterHash(c),approvalId:'inert-only',expiresAt:Date.now()+60000,journalPath:path};
 const caller=new AbortController(),entered=deferred(),release=deferred();let starts=0,reads=0,http=0,reserves=0,active=0;const launches:string[]=[],cancelled:number[]=[];
 const text=(k:number)=>k<2?(scenario==='objective'?'5':'4'):JSON.stringify({verdict:scenario==='split'&&k===3?'FAIL':'PASS',suspect:false});
 const bindings=Object.fromEntries(models.map((id,k)=>[id,{model:{id,provider:'openai-codex',api:'openai-codex-responses',baseUrl:'https://chatgpt.com/backend-api'},stream:(_m:any,ctx:any,o:any)=>({result:async()=>{const body=o.onPayload({model:id,store:false,stream:true,instructions:ctx.systemPrompt,input:[{role:'user',content:[{type:'input_text',text:ctx.messages[0].content}]}],text:{verbosity:'low'},include:['reasoning.encrypted_content'],tool_choice:'none',reasoning:{effort:'low',summary:'auto'}});await o.fetch(c.destination,{method:'POST',body:JSON.stringify(body)});return {model:id,provider:'openai-codex',api:'openai-codex-responses',stopReason:'stop',content:[{type:'text',text:text(k)}]};}})}]));
 const ports:any={bindings,credentials:{kind:'fixture-oauth',read:async()=>{reads++;return {type:'oauth',provider:'openai-codex',access:'fixture.'+Buffer.from(JSON.stringify({'https://api.openai.com/auth':{chatgpt_account_id:'fixture-account'}})).toString('base64url')+'.invalid',expires:Date.now()+60000,accountId:'fixture-account'};}},transport:{kind:'fixture-http',exchange:async(wire:any,_credential:any,signal:AbortSignal)=>{const k=models.indexOf(JSON.parse(wire.body.toString()).model);http++;if(scenario==='cancel'){entered.resolve();await new Promise((_,reject)=>{const stop=()=>reject(Error('cancelled'));signal.addEventListener('abort',stop,{once:true});if(signal.aborted)stop();});}const item={id:'item-'+k,type:'message',role:'assistant',status:'completed',content:[{type:'output_text',text:text(k)}]};const events=[{type:'response.created',response:{id:'response-'+k,status:'in_progress'}},{type:'response.output_item.added',output_index:0,item:{...item,status:'in_progress',content:[]}},{type:'response.output_text.delta',output_index:0,content_index:0,item_id:item.id,delta:text(k)},{type:'response.output_item.done',output_index:0,item},{type:'response.completed',response:{id:'response-'+k,model:models[k],status:'completed',output:[item]}}];return new Response(events.map((e,sequence_number)=>'data: '+JSON.stringify({...e,sequence_number})+'\n\n').join(''),{headers:{'content-type':'text/event-stream'}});}}};
 const owner={reserveBatch:async(demands:any[])=>{reserves++;if(scenario==='exhausted')throw Error('EXHAUSTED');active=demands.length;return demands.map((_:any,k:number)=>({settle:async()=>{cancelled.push(k);active--;}}));}};
 const producer:any={producerIpcDemand:(binding:any)=>binding,createProducerIpcHost:(v:any)=>v,startProducerIpc:async(v:any)=>{starts++;launches.push(v.binding.invocationId);const completion=(async()=>{const references=await v.host.exchange(Readable.from([JSON.stringify({id:v.binding.invocationId,sequence:1})+'\n']),{binding:v.binding,signal:v.signal});if(scenario==='held'||scenario==='unacknowledged'){entered.resolve();await release.promise;}if(scenario!=='unknown')active--;return {binding:v.binding,outcome:scenario==='failed'?'failed':'completed',settlement:scenario==='unknown'?'unknown':'acknowledged',childState:'settled',hostState:'acknowledged',frameSha256:sha(JSON.stringify({id:v.binding.invocationId,sequence:1})+'\n'),acceptance:'not-assessed',references};})();return {completion,result:Promise.resolve({outcome:scenario==='unacknowledged'?'timed-out':'pending'}),inspect:()=>({outcome:'pending'})};}};
 const source:any={producer,owner,signal:caller.signal,bindings:ids.map((invocationId,k)=>({version:'producer-ipc-v1',budgetDigest:'b'.repeat(64),orderId:'order',experimentId:'experiment',executionId:'execution-'+k,charterSha256:approval.charterSha256,invocationId}))};
 return {path,c,approval,ports,source,caller,entered,release,run:()=>executeProducerCodexQualification(path,c,approval,ports,source),counts:()=>({starts,reads,http,reserves,active,cancelled,launches})};
}
function singleWorld(scenario='normal',proposer='gpt-5.4'){
 const w=world(scenario,proposer);Object.assign(w.c.invocations[0],{input:'Return only the integer: 2 + 2.',instructions:'Return only the integer answer.'});w.approval.charterSha256=codexCharterHash(w.c);for(const b of w.source.bindings)b.charterSha256=w.approval.charterSha256;
 const approval:any={...w.approval,scope:'fixture-single-request',approvedCalls:1};return {...w,singleApproval:approval,single:()=>executeProducerCodexSingleRequest(w.path,w.c,approval,w.ports,w.source)};
}
function astraWorld(scenario='normal'){
 const w=singleWorld(scenario,'gpt-6-astra'),path=new URL('./fixtures/codex-astra-definition.json',import.meta.url).pathname;
 w.c.diagnosticModel={path,sha256:sha(readFileSync(path,'utf8'))};w.ports.bindings['gpt-6-astra'].model=loadCodexDiagnosticModel(w.c.diagnosticModel);w.singleApproval.charterSha256=codexCharterHash(w.c);for(const b of w.source.bindings)b.charterSha256=w.singleApproval.charterSha256;return w;
}
it.each(['normal','failed','unknown'])('pinned Astra %s preserves one request and original accounting',async scenario=>{const w=astraWorld(scenario);if(scenario==='normal')expect(await w.single()).toMatchObject({calls:1,httpAttempts:1,panel:null,objective:'PASS'});else await expect(w.single()).rejects.toThrow();expect(w.counts()).toMatchObject({http:1,starts:1,reserves:1,cancelled:[1,2,3,4],active:scenario==='unknown'?1:0});const rows=learningJournal(w.path).read().map(r=>r.value),request=JSON.parse(String(rows.find(r=>r.type==='host-write-completed')!.requestBody));expect(request).toMatchObject({model:'gpt-6-astra',instructions:'Return only the integer answer.',input:[{role:'user',content:[{type:'input_text',text:'Return only the integer: 2 + 2.'}]}],reasoning:{effort:'low'}});expect(rows.filter(r=>r.type==='producer-ipc-settled')).toHaveLength(scenario==='normal'?1:0);expect(rows.some(r=>r.type==='panel')).toBe(false);});
it.each(['pin','sdk','effort','duplicate','missing-definition','full-flow'])('pinned Astra refuses %s before effects',async change=>{const w=astraWorld();if(change==='pin')w.c.diagnosticModel.sha256='0'.repeat(64);if(change==='sdk')w.ports.bindings['gpt-6-astra'].model.maxTokens++;if(change==='effort')w.c.invocations[0].effort='medium';if(change==='duplicate')w.c.rolePolicy[1].model='gpt-6-astra';if(change==='missing-definition')delete w.c.diagnosticModel;w.singleApproval.charterSha256=codexCharterHash(w.c);for(const b of w.source.bindings)b.charterSha256=w.singleApproval.charterSha256;if(change==='full-flow'){w.approval.charterSha256=codexCharterHash(w.c);await expect(w.run()).rejects.toThrow();}else await expect(w.single()).rejects.toThrow();expect(w.counts()).toMatchObject({http:0,reads:0,starts:0,reserves:0});});
it.each(['normal','objective','failed','unknown'])('single diagnostic bounds %s to one callable claim and cancels unused four',async scenario=>{
 const w=singleWorld(scenario);if(['failed','unknown'].includes(scenario))await expect(w.single()).rejects.toThrow();else{const r:any=await w.single();expect(r).toMatchObject({diagnostic:'single-request-v1',calls:1,httpAttempts:1,objective:scenario==='objective'?'FAIL':'PASS',liveQualified:false,panel:null});}
 expect(w.counts()).toMatchObject({starts:1,http:1,reserves:1,launches:['proposer'],cancelled:[1,2,3,4]});const rows=learningJournal(w.path).read().map(r=>r.value);expect(rows[0].spec).toMatchObject({maxCalls:1,invocations:[{id:'proposer'}]});expect(rows.filter(r=>r.type==='claim')).toHaveLength(1);expect(rows.some(r=>r.type==='panel')).toBe(false);expect(w.counts().active).toBe(scenario==='unknown'?1:0);expect(rows.filter(r=>r.type==='producer-ipc-settled')).toHaveLength(['normal','objective'].includes(scenario)?1:0);
 const before=w.counts();if(['failed','unknown'].includes(scenario))await expect(w.single()).rejects.toThrow();else await w.single();expect(w.counts()).toEqual(before);
 await expect(w.run()).rejects.toThrow();expect(w.counts()).toEqual(before);
});
it.each(['budget','scope','prompt','model','expected','source'])('single diagnostic refuses %s mismatch before reservation',async change=>{const w=singleWorld();if(change==='budget')w.singleApproval.approvedCalls=5;if(change==='scope')w.singleApproval.scope='fixture';if(change==='prompt')w.c.invocations[0].input='other';if(change==='model')w.c.invocations[0].model='gpt-5.5';if(change==='expected')w.c.invocations[0].expectedSha256=sha('5');if(['prompt','model','expected'].includes(change)){w.singleApproval.charterSha256=codexCharterHash(w.c);for(const b of w.source.bindings)b.charterSha256=w.singleApproval.charterSha256;}await expect(executeProducerCodexSingleRequest(w.path,w.c,w.singleApproval,w.ports,change==='source'?undefined as any:w.source)).rejects.toThrow();expect(w.counts()).toMatchObject({starts:0,http:0,reads:0,reserves:0});});
it.each(['http-failure','sdk-retry'])('single %s never makes a second transport request',async scenario=>{const w=singleWorld();if(scenario==='http-failure'){const send=w.ports.transport.exchange;w.ports.transport.exchange=async(...args:any[])=>{await send(...args);return new Response('fixture refusal',{status:400});};}else{const binding=w.ports.bindings['gpt-5.4'],stream=binding.stream;binding.stream=(m:any,c:any,o:any)=>stream(m,c,{...o,fetch:async(...args:any[])=>{const r=await o.fetch(...args);await o.fetch(...args);return r;}});}await expect(w.single()).rejects.toThrow();expect(w.counts()).toMatchObject({starts:1,http:1,reserves:1,cancelled:[1,2,3,4]});expect(learningJournal(w.path).read().some(r=>r.value.type==='subscription-finished')).toBe(false);});
it('single success cannot finish when unused original cancellation is unacknowledged',async()=>{const w=singleWorld(),reserve=w.source.owner.reserveBatch;w.source.owner.reserveBatch=async(d:any[])=>{const permits=await reserve(d);permits[4].settle=async()=>{throw Error('unknown original cancellation');};return permits;};await expect(w.single()).rejects.toThrow('queued original settlement unknown');expect(w.counts()).toMatchObject({http:1,starts:1,reserves:1});expect(learningJournal(w.path).read().some(r=>r.value.type==='subscription-finished')).toBe(false);});
it('single approval cannot authorize normal five-role API',async()=>{const w=singleWorld();await expect(executeProducerCodexQualification(w.path,w.c,w.singleApproval,w.ports,w.source)).rejects.toThrow();expect(w.counts().reserves).toBe(0);});
it('single diagnostic preserves original cancellation and no next role',async()=>{const w=singleWorld('cancel');const pending=w.single();const rejected=expect(pending).rejects.toThrow();await w.entered.promise;w.caller.abort();await rejected;expect(w.counts()).toMatchObject({starts:1,http:1,cancelled:[1,2,3,4]});});
it.each([['normal',4],['split',5],['objective',1]])('composes %s with one whole reservation, original settlement and counted unused slots',async(s,n)=>{const w=world(s),r:any=await w.run();expect(r.calls).toBe(n);expect(r.sourceKind).toBe('producer-ipc-v1');expect(w.counts()).toMatchObject({starts:n,http:n,reserves:1,active:0});expect(w.counts().cancelled).toHaveLength(5-Number(n));const again=await w.run();expect(again).toEqual(r);expect(w.counts().reserves).toBe(1);await expect(executeCodexQualification(w.path,w.c,w.approval,w.ports)).rejects.toThrow('source');});
it.each(['charter','approval','path','sdk','port','binding','preabort'])('validates %s before reservation/source/credential effects',async(change)=>{const w=world();if(change==='charter')w.c.invocations[0].input+='changed';if(change==='approval')w.approval.expiresAt=0;if(change==='path')w.approval.journalPath+='/other';if(change==='sdk')w.ports.bindings[w.c.invocations[4].model].model.provider='other';if(change==='port')w.ports.transport.kind='subscription-http';if(change==='binding')w.source.bindings[4].charterSha256='c'.repeat(64);if(change==='preabort')w.caller.abort();await expect(w.run()).rejects.toThrow();expect(w.counts()).toMatchObject({starts:0,reads:0,http:0,reserves:0});});
it('refuses a concurrent caller while reservation is pending, before any source call',async()=>{const w=world(),reserve=w.source.owner.reserveBatch;w.source.owner.reserveBatch=async(d:any[])=>{const permits=await reserve(d);w.entered.resolve();await w.release.promise;return permits;};const pending=w.run();await w.entered.promise;expect(w.counts().starts).toBe(0);await expect(w.run()).rejects.toThrow('stranded');w.release.resolve();await pending;expect(w.counts().reserves).toBe(1);});
it('does not cache success when an original queued permit fails to acknowledge cancellation',async()=>{const w=world(),reserve=w.source.owner.reserveBatch;let attempts=0;w.source.owner.reserveBatch=async(d:any[])=>{const p=await reserve(d),settle=p[4].settle;p[4].settle=async()=>{attempts++;await settle();throw Error('inert uncertain queue settlement');};return p;};await expect(w.run()).rejects.toThrow('queued original settlement unknown');expect(attempts).toBe(1);expect(learningJournal(w.path).read().some(e=>e.value.type==='subscription-finished')).toBe(false);await expect(w.run()).rejects.toThrow();expect(attempts).toBe(1);});
it('refuses different source identities even when a matching charter previously finished',async()=>{const w=world();await w.run();w.source.bindings[4].executionId='changed-execution';await expect(w.run()).rejects.toThrow('source');expect(w.counts()).toMatchObject({starts:4,reserves:1});});
it('does not advance or re-reserve a stranded run while original completion is pending',async()=>{const w=world('held'),pending=w.run();await w.entered.promise;expect(w.counts().launches).toEqual(['proposer']);await expect(w.run()).rejects.toThrow('stranded');expect(w.counts().reserves).toBe(1);w.release.resolve();await pending;});
it('refuses missing opt-in source rather than falling back to host frames',async()=>{const w=world();await expect(executeProducerCodexQualification(w.path,w.c,w.approval,w.ports,undefined as any)).rejects.toThrow();expect(w.counts()).toMatchObject({starts:0,reads:0,reserves:0});});
it('bounds observation without manufacturing settlement for an unacknowledged original source',async()=>{const w=world('unacknowledged');await expect(w.run()).rejects.toThrow();expect(w.counts().launches).toEqual(['proposer']);expect(w.counts().active).toBe(1);expect(w.counts().cancelled).toEqual([1,2,3,4]);w.release.resolve();});
it('retains aggregate host exhaustion and never retries a partially consumed run',async()=>{const w=world();w.c.limits.totalRequestBytes=4096;w.approval.charterSha256=codexCharterHash(w.c);for(const b of w.source.bindings)b.charterSha256=w.approval.charterSha256;await expect(w.run()).rejects.toThrow();expect(w.counts().http).toBe(1);expect(learningJournal(w.path).read().some(e=>e.value.type==='subscription-reservation-refused')).toBe(true);const before=w.counts();await expect(w.run()).rejects.toThrow();expect(w.counts()).toEqual(before);});
it.each(['failed','unknown','exhausted'])('refuses %s and never retries or releases claimed unknown ownership',async(s)=>{const w=world(s);await expect(w.run()).rejects.toThrow();const before=w.counts();await expect(w.run()).rejects.toThrow();expect(w.counts()).toEqual(before);expect(before.starts).toBe(s==='exhausted'?0:1);if(s==='unknown')expect(before.active).toBe(1);});
it('forwards original cancellation and never launches the next role',async()=>{const w=world('cancel'),pending=w.run();const assertion=expect(pending).rejects.toThrow();await w.entered.promise;w.caller.abort();await assertion;expect(w.counts()).toMatchObject({starts:1,http:1,reserves:1});expect(w.counts().cancelled).toEqual([1,2,3,4]);});
