import { expect,it } from 'vitest';
import { inertCodexSdkStreams } from '../src/codex-sdk-transport.js';
const model={id:'gpt-6-astra',provider:'openai-codex',api:'openai-codex-responses',baseUrl:'https://chatgpt.com/backend-api'};
const request={model:model.id,instructions:'Integer only',input:[{role:'user',content:[{type:'input_text',text:'2 + 2'}]}],reasoning:{effort:'low'},parallel_tool_calls:false};
function body(){const item={id:'synthetic-item',type:'message',role:'assistant',status:'completed',content:[{type:'output_text',text:'4'}]};return [{type:'response.created',response:{id:'synthetic-response',status:'in_progress'}},{type:'response.output_item.added',output_index:0,item:{...item,status:'in_progress',content:[]}},{type:'response.output_text.delta',output_index:0,content_index:0,item_id:item.id,delta:'4'},{type:'response.output_item.done',output_index:0,item},{type:'response.completed',response:{id:'synthetic-response',model:model.id,status:'completed',output:[item]}}].map((e,sequence_number)=>'data: '+JSON.stringify({...e,sequence_number})+'\n\n').join('');}
it('retains distinct closed response failure categories, preserves original errors and leaves success unchanged',async()=>{
 for(const scenario of ['success','missing','other','sse','record','diagnostic-recorder-fails']){
  const records:any[]=[],original=Error('synthetic initiating recorder error'),secondary=Error('synthetic secondary recorder error');let calls=0;
  const stream=(_m:any,_c:any,o:any)=>({result:async()=>{o.onPayload(request);await o.fetch('https://chatgpt.com/backend-api/codex/responses',{method:'POST',body:JSON.stringify(request)});return {model:model.id,provider:model.provider,api:model.api,stopReason:'stop',content:[{type:'text',text:'4'}]};}});
  const ports=inertCodexSdkStreams({model,stream},async()=>{calls++;return new Response(Buffer.from(scenario==='sse'?'synthetic malformed SSE':body()),{headers:scenario==='missing'?{}:{'content-type':scenario==='other'?'application/x-synthetic-private-header':'text/event-stream'}});},r=>{if(r.type==='sdk-response-validated'&&['record','diagnostic-recorder-fails'].includes(scenario))throw original;if(r.type==='sdk-response-failed'&&scenario==='diagnostic-recorder-fails')throw secondary;records.push(r);});
  const chunks:Buffer[]=[];const done=new Promise<void>((resolve,reject)=>{ports.response.on('data',b=>chunks.push(b));ports.response.once('end',resolve);ports.response.once('error',reject);ports.transport.once('error',reject);});ports.transport.end(JSON.stringify(request));
  try{if(scenario==='success'){await done;expect(Buffer.concat(chunks).toString()).toBe('4');expect(records.some(r=>r.type==='sdk-response-failed')).toBe(false);expect(records.some(r=>r.type==='sdk-decoded')).toBe(true);}else{const error=await done.then(()=>null,e=>e);expect(error).toBeInstanceOf(Error);if(['record','diagnostic-recorder-fails'].includes(scenario))expect(error).toBe(original);expect(records.some(r=>r.type==='sdk-decoded')).toBe(false);if(scenario!=='diagnostic-recorder-fails')expect(records.find(r=>r.type==='sdk-response-failed')).toEqual({type:'sdk-response-failed',category:scenario==='sse'?'SSE-validation-failed':scenario==='record'?'validation-record-failed':'media-type-invalid',mediaType:scenario==='missing'?'missing':scenario==='other'?'other':'event-stream',liveQualified:false});}expect(calls).toBe(1);}finally{ports.transport.destroy();ports.response.destroy();}
 }
});
