import { expect, it } from 'vitest';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import { Readable, Writable } from 'node:stream';
import { createLocalCodexHost, openLocalCodexHost } from '../src/codex-host-observer.js';
const sha=(s:string)=>createHash('sha256').update(s).digest('hex');
const vote=(v:string)=>JSON.stringify({verdict:v,suspect:false});
const models=['gpt-5.6-sol','gpt-5.5','gpt-5.3-codex-spark','gpt-5.4-mini'];
function setup(){const path=join(mkdtempSync(join(tmpdir(),'codex-panel-')),'host');const host=createLocalCodexHost(path,{version:'codex-host-local-v1',maxCalls:4,wallMs:3000,invocations:['subject','first','second','tie'].map((id,i)=>({id,role:i?'judge':'subject',model:models[i],effort:'low',instructions:i?'Judge this anonymous output.':'Return the integer.',input:i?'Must be 4.':'2+2?',expectedSha256:sha('4'),subjectId:i?'subject':null}))});const policy=[{role:'proposer',model:'gpt-5.4',canonical:'fixture-p',lineage:'fixture-p'},...models.map((model,i)=>({role:i?'judge':'subject',model,canonical:`fixture-${i}`,lineage:`fixture-${i}`}))] as any;return {path,host,policy};}
async function exchange(host:ReturnType<typeof createLocalCodexHost>,id:string,response:string){const chunks:Buffer[]=[];const out=new Writable({write(b,_e,cb){chunks.push(Buffer.from(b));cb();}});const result=await host.exchange(Readable.from([JSON.stringify({id,sequence:1})+'\n']),out,Readable.from([response]));return {body:Buffer.concat(chunks).toString(),result};}
it.each(['{"verdict":"pass","suspect":false}','{"verdict":"PASS","suspect":false,"extra":"synthetic"}','{"verdict":"pass","suspect":false,"extra":"synthetic"}','{"verdict":"PASS","suspect":"false"}','{"verdict":"PASS"}','not JSON'])('rejects nonconforming final vote without normalization %#',async response=>{const {host,policy}=setup();await exchange(host,'subject','4');await expect(exchange(host,'first',response)).rejects.toThrow();expect(host.inspect()).toMatchObject({calls:2,aborted:true,complete:false});expect(()=>host.panel('subject',['first','second'],policy)).toThrow();});
it('blocks judge emission before objective eligibility',async()=>{const {host}=setup();await expect(exchange(host,'first',vote('PASS'))).rejects.toThrow(/objective/);expect(host.inspect().calls).toBe(0);});
it('binds host bytes to objective-before-blind split panel and durable reopen',async()=>{const {host,path,policy}=setup();await exchange(host,'subject','4');const first=await exchange(host,'first',vote('PASS'));expect(first.body).not.toContain('gpt-5.6-sol');expect(first.body).toContain('outputBase64');await exchange(host,'second',vote('FAIL'));await exchange(host,'tie',vote('PASS'));const r=host.panel('subject',['first','second','tie'],policy);expect(r.collapse.verdict).toBe('PASS');expect(r.liveQualified).toBe(false);expect(r.routingDefault).toBeNull();expect(openLocalCodexHost(path).panel('subject',['first','second','tie'],policy)).toEqual(r);});
it('refuses an unnecessary tie-break and does not turn missing lineage into qualified votes',async()=>{const {host,policy}=setup();await exchange(host,'subject','4');await exchange(host,'first',vote('PASS'));await exchange(host,'second',vote('PASS'));expect(host.panel('subject',['first','second'],policy.map((r:any)=>({...r,lineage:null})))).toMatchObject({liveQualified:false,disclosures:['lineage unresolved; correlation unknown']});await expect(exchange(host,'tie',vote('PASS'))).rejects.toThrow(/split/);expect(host.inspect().calls).toBe(3);});
