import { beforeEach, afterEach, expect, it, vi } from 'vitest';
import { EventEmitter } from 'node:events';
const f=vi.hoisted(()=>({request:vi.fn(),status:400,body:'{}',authorized:true,complete:true,detach:true,encoding:undefined as string|undefined,written:true,termination:'end',socketMutation:'none',contentType:'application/json',records:[] as any[]}));
vi.mock('node:https',()=>({Agent:class{destroy(){}},request:(o:any,cb:any)=>f.request(o,cb)}));
import { createCodexHttpsPort } from '../src/codex-https.js';
const credential=()=>({type:'oauth' as const,provider:'openai-codex' as const,accountId:'fixture-response-account',expires:Date.now()+60000,access:Buffer.from('{"alg":"RS256"}').toString('base64url')+'.'+Buffer.from(JSON.stringify({'https://api.openai.com/auth':{chatgpt_account_id:'fixture-response-account'}})).toString('base64url')+'.'+Buffer.from('invalid-fixture-signature').toString('base64url')});
const limits={calls:5,requestBytes:4096,responseBytes:16384,totalRequestBytes:20480,totalResponseBytes:81920,callMs:1000,wallMs:5000};
const run=(record=(v:any)=>f.records.push(v))=>createCodexHttpsPort().exchange({destination:'https://chatgpt.com/backend-api/codex/responses',method:'POST',body:Buffer.from('{}'),encoding:null},credential(),new AbortController().signal,record,limits);
beforeEach(()=>{
 for(const k of ['HTTP_PROXY','HTTPS_PROXY','ALL_PROXY','http_proxy','https_proxy','all_proxy','NODE_EXTRA_CA_CERTS','NODE_TLS_REJECT_UNAUTHORIZED'])vi.stubEnv(k,'');
 Object.assign(f,{status:400,body:'{}',authorized:true,complete:true,detach:true,encoding:undefined,written:true,termination:'end',socketMutation:'none',contentType:'application/json',records:[]});
 f.request.mockImplementation((_o,cb)=>{const req:any=new EventEmitter();req.destroy=vi.fn();req.end=()=>queueMicrotask(()=>{if(f.written)req.emit('finish');const res:any=new EventEmitter();res.statusCode=f.status;res.headers={'content-type':f.contentType,...(f.encoding?{'content-encoding':f.encoding}:{})};res.socket={authorized:f.authorized};res.complete=f.complete;res.aborted=false;cb(res);res.emit('data',Buffer.from(f.body));if(f.socketMutation==='replace-trusted')res.socket={authorized:true};if(f.socketMutation==='invalidate-captured')res.socket.authorized=false;if(f.detach)res.socket=null;res.emit(f.termination);});return req;});
});
afterEach(()=>vi.unstubAllEnvs());
it.each([400,401,429])('retains safe completed %s refusal after Node detaches the socket',async status=>{
 f.status=status;f.body=JSON.stringify({error:{message:'SECRET_ACCOUNT_DETAIL',type:'invalid_request_error',code:'unsupported_parameter',param:'tool_choice'}});
 const response=await run();expect(response.status).toBe(status);expect(response.ok).toBe(false);expect(await response.text()).not.toContain('SECRET');
 expect(f.records.find(r=>r.bodySha256)).toMatchObject({status,tlsAuthorized:true,complete:true,refusal:{type:'invalid_request_error',code:'unsupported_parameter',parameter:'tool_choice'}});expect(JSON.stringify(f.records)).not.toContain('SECRET');
});
it('preserves a valid completed200 without weakening body validation',async()=>{f.status=200;f.body='fixture data';expect(await (await run()).text()).toBe('fixture data');expect(f.records.find(r=>r.bodySha256).complete).toBe(true);});
it.each(['tls-unverified','message-incomplete','response-encoding','response-byte-limit','redirect','write-incomplete','response-aborted','response-closed'])('rejects and records bounded completion reason %s',async reason=>{
 if(reason==='tls-unverified')f.authorized=false;if(reason==='message-incomplete')f.complete=false;if(reason==='response-encoding')f.encoding='gzip';if(reason==='response-byte-limit')f.body='x'.repeat(16385);if(reason==='redirect')f.status=302;if(reason==='write-incomplete')f.written=false;if(reason==='response-aborted')f.termination='aborted';if(reason==='response-closed')f.termination='close';
 await expect(run()).rejects.toThrow(/^subscription-http-failed$/);expect(f.records.find(r=>r.classification==='response-refused')).toEqual({type:'http-request-failed',classification:'response-refused',phase:'response',reason});expect(f.records.some(r=>r.bodySha256)).toBe(false);
});
it.each([200,400,401,429])('rejects credential reflection at status%s BEFORE body hashing',async status=>{f.status=status;f.body=JSON.stringify({error:{message:credential().access}});await expect(run()).rejects.toThrow(/^subscription-http-failed$/);expect(f.records.some(r=>r.bodySha256)).toBe(false);expect(f.records.find(r=>r.reason)?.reason).toBe('credential-reflection');expect(JSON.stringify(f.records)).not.toContain(credential().access);});
it('rejects escaped JSON token and account reflections without hashing them',async()=>{for(const value of [credential().access,credential().accountId]){f.records=[];f.body=JSON.stringify({error:{message:value}}).replaceAll(value[0],'\\u'+value.charCodeAt(0).toString(16).padStart(4,'0'));await expect(run()).rejects.toThrow(/^subscription-http-failed$/);expect(f.records.some(r=>r.bodySha256)).toBe(false);expect(f.records.find(r=>r.reason)?.reason).toBe('credential-reflection');}});
it.each(['not json',JSON.stringify({error:{type:'SECRET',code:'SECRET',param:'SECRET',message:'SECRET'}}),JSON.stringify({error:{type:{private:'SECRET'},code:7,param:['SECRET']}})])('maps unknown/malformed refusal fields to unknown',async body=>{f.body=body;await run();expect(f.records.find(r=>r.bodySha256).refusal).toEqual({type:'unknown',code:'unknown',parameter:'unknown'});expect(JSON.stringify(f.records)).not.toContain('SECRET');});
it.each(['replace-trusted','invalidate-captured'])('checks original TLS authorization despite %s socket mutation',async mutation=>{f.socketMutation=mutation;f.authorized=mutation!=='replace-trusted';f.detach=false;await expect(run()).rejects.toThrow(/^subscription-http-failed$/);expect(f.records.find(r=>r.reason)?.reason).toBe('tls-unverified');});
it('records only a fixed internal reason when response construction fails',async()=>{f.status=200;f.contentType='SECRET\nHEADER';await expect(run()).rejects.toThrow(/^subscription-http-failed$/);expect(f.records.find(r=>r.reason)?.reason).toBe('internal-completion');expect(f.records.some(r=>r.bodySha256)).toBe(false);expect(JSON.stringify(f.records)).not.toContain('SECRET');});
it('rejects when completed-response or completion-failure recording throws',async()=>{
 for(const invalid of [false,true]){f.authorized=!invalid;await expect(run(v=>{if(v.complete||v.classification==='response-refused')throw Error('SECRET_RECORDER');})).rejects.toThrow(/^subscription-http-failed$/);}
});
