import { afterEach, expect, it } from 'vitest';
import { readFileSync, rmSync, unlinkSync, cpSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { openLearningWorkspace, createLearningWorkspace, catalogLearningArchive } from '../src/learning-workspace.js';
import { openBlindIntervention } from '../src/blind-intervention.js';
import { readLearningLifecycle } from '../src/learning-lifecycle.js';
import { readArchiveSource } from '../src/evidence-archive.js';
import { previewLearningTrust, configureLearningTrust, previewLearningCaseLabel } from '../src/learning-trust-setup.js';
import { learningWorkspaceFixture, sha } from './learning-workspace-fixture.js';
import { retainWorkSignalObservation } from '../src/work-signal-observation.js';
import { captureWorkSignalCases } from '../src/work-signal-cases.js';
const roots:string[]=[];
const fixture=()=>{const f=learningWorkspaceFixture();roots.push(f.root);return f;};
afterEach(()=>{for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true});});
it('exposes named retained learning without reveal, attention, decisions or dispatch on read',()=>{
  const f=fixture(),file=join(f.directory,'events.jsonl'),before=readFileSync(file);
  const v=f.workspace.inspect(Date.now());
  expect(v).toMatchObject({mode:'deliberate-review',automaticExposureReserved:false,delegationStarted:false,acceptance:'not-assessed',trust:{state:'deferred',automaticExposure:{mode:'silent',reason:'policy-unavailable'}}});
  expect(f.workspace.comparison('reports')).toMatchObject({qualityScope:null,revealReady:false,activation:'not-activated',priorFeedback:[{manifestId:f.feedback,scope:'prior-feedback-only'}]});
  expect(JSON.stringify(f.workspace.comparison('reports'))).not.toMatch(/fixture:subject|costUnit|cheapestEligible/);
  expect(()=>f.workspace.reveal('reports')).toThrow(/quality/);
  expect(openLearningWorkspace(f.directory).inspect(Date.now()).comparisons).toEqual(v.comparisons);
  expect(readFileSync(file)).toEqual(before);
  expect(catalogLearningArchive(f.archiveRoot,f.config.author).map(c=>c.kind).sort()).toEqual(['cases','comparison']);
});
it('rejects excerpt acknowledgements and invalid choices before claiming, and persists full-scope quality before reveal',()=>{
  const f=fixture(),view=f.workspace.comparison('reports'),file=join(f.directory,'events.jsonl'),before=readFileSync(file);
  expect(()=>f.workspace.choose('reports',{kind:'one',labels:[view.cards[0].label]},{scope:'full-artifacts',note:'Excerpt only',reviewedArtifactDigests:[f.hashes[0]]})).toThrow(/complete/);
  expect(()=>f.workspace.choose('reports',{kind:'one',labels:['unknown']},{scope:'full-artifacts',note:'Bad label',reviewedArtifactDigests:f.hashes})).toThrow(/quality/);
  expect(readFileSync(file)).toEqual(before);
  f.quality();const reopened=openLearningWorkspace(f.directory);
  expect(reopened.comparison('reports')).toMatchObject({revealReady:true,qualityScope:'full-artifacts'});
  expect(reopened.reveal('reports').arms).toHaveLength(2);
  expect(()=>reopened.choose('reports',{kind:'none',labels:[]},{scope:'full-artifacts',note:'Changed mind',reviewedArtifactDigests:f.hashes})).toThrow(/locked/);
  expect(readArchiveSource(f.archiveRoot,f.feedback)).toMatchObject({status:'available',bytes:Buffer.from('Historical fixture: preferred excerpt A; both acceptable. Excerpts only.')});
});
it('does not upgrade legacy quality into full-artifact review automatically',()=>{
  const f=fixture(),blind=openBlindIntervention(f.archiveRoot,f.comparisonManifestId,f.config.author);blind.choose({kind:'none',labels:[]});
  expect(f.workspace.comparison('reports')).toMatchObject({qualityScope:'legacy-unscoped',revealReady:false});
  expect(()=>f.workspace.reveal('reports')).toThrow(/full-artifact/);
});
it('retains reject/defer independently of quality, with exact prior-decision CAS and no activation',()=>{
  const f=fixture(),defer=f.workspace.decide('reports',{disposition:'defer',note:'Need complete review',priorDecisionId:null});
  expect(()=>f.workspace.decide('reports',{disposition:'reject',note:'Stale request',priorDecisionId:null})).toThrow(/stale/);
  const rejected=f.workspace.decide('reports',{disposition:'reject',note:'Not useful for this scope',priorDecisionId:defer.id});
  expect(openLearningWorkspace(f.directory).comparison('reports')).toMatchObject({decision:rejected,choice:null,activation:'not-activated'});
});
it('requires current independent adoption authority/facts, original activation, explicit rollback and outcome authority',()=>{
  const f=fixture();f.quality();f.workspace.decide('reports',{disposition:'adopt',note:'Fixture intent',priorDecisionId:null});
  expect(()=>f.workspace.prepareAdoption('reports',null,f.facts,Date.now())).toThrow(/authority/);
  expect(()=>f.workspace.prepareAdoption('reports',f.authority,{...f.facts,eligible:false},Date.now())).toThrow(/ineligible/);
  const receipt=f.workspace.prepareAdoption('reports',f.authority,f.facts,Date.now());
  expect(f.workspace.comparison('reports').activation).toBe('not-activated');
  const observation={id:'fixture-later',adoptionId:receipt.id,candidateDigest:receipt.candidateDigest,scopeDigest:receipt.scopeDigest,originalRequirementDigest:sha('original'),currentRequirementDigest:sha('changed'),outcome:'success' as const,acceptanceDigest:null,acceptedArtifactDigest:null,observedArtifactDigest:f.hashes[0],evidence:[f.caseManifestId]};
  expect(()=>f.workspace.previewObservation('reports',observation)).toThrow(/activation/);
  const activation=f.registry({operation:'activate',requestId:'fixture-activation',adoptionId:receipt.id,scopeDigest:receipt.scopeDigest,candidateDigest:receipt.candidateDigest,revision:1});
  expect(()=>f.workspace.linkActivation('reports',activation,[])).toThrow(/authority/);f.workspace.linkActivation('reports',activation,[activation]);
  expect(f.workspace.comparison('reports').adoptionReadiness).toMatchObject({state:'activation-recorded',reason:expect.stringContaining('original activation receipt linked')});
  const preview=f.workspace.previewObservation('reports',observation);
  expect(preview.classification).toMatchObject({state:'changed-requirements',automaticRollback:false});
  expect(()=>f.workspace.observe('reports',observation,[])).toThrow(/authority/);f.workspace.observe('reports',observation,[preview.digest],'fixture-independent-human');
  const request=f.workspace.previewRollback('reports','operator-request',[f.caseManifestId]);
  expect(()=>f.workspace.prepareRollback('reports',request,f.authority,Date.now(),{adoptionId:receipt.id,candidateDigest:receipt.candidateDigest,scopeDigest:receipt.scopeDigest})).toThrow(/authority/);
  expect(f.workspace.prepareRollback('reports',request,{...f.authority,rollbacks:[request.id]},Date.now(),{adoptionId:receipt.id,candidateDigest:receipt.candidateDigest,scopeDigest:receipt.scopeDigest})).toMatchObject({application:'not-performed'});
  expect(f.workspace.comparison('reports').rollback).toBe('not-recorded');
  const rollback=f.registry({operation:'rollback',requestId:request.id,adoptionId:receipt.id,scopeDigest:receipt.scopeDigest,candidateDigest:receipt.rollbackCandidateDigest,revision:2});f.workspace.linkRollback('reports',rollback,[rollback]);
  expect(f.workspace.comparison('reports').adoptionReadiness).toMatchObject({state:'rollback-recorded',reason:expect.stringContaining('original registry rollback recorded')});
  const lifecycle=f.workspace.lifecycle('reports');expect(lifecycle.state).toBe('linked');
  expect(readLearningLifecycle(f.archiveRoot,lifecycle.manifestId!).links).toMatchObject({adoption:activation,rollback,outcomes:[f.workspace.comparison('reports').outcomes[0].manifestId]});
});
it('renders stale case, missing artifact and missing registry receipts as defer reasons',()=>{
  const f=fixture();f.workspace.decideCase('daily',{caseManifestId:f.caseManifestId,priorDecisionId:f.decision.id,disposition:'expected_behavior',note:'Independent correction'});
  expect(f.workspace.inspect(Date.now()).comparisons[0]).toMatchObject({state:'deferred',reason:expect.stringMatching(/stale/)});
  const g=fixture();g.quality();unlinkSync(join(g.archiveRoot,'objects',g.hashes[0]));
  expect(g.workspace.inspect(Date.now()).comparisons[0]).toMatchObject({state:'deferred',reason:expect.stringMatching(/artifact/)});
  g.workspace.decide('reports',{disposition:'defer',note:'Artifact unavailable; no acceptance implied',priorDecisionId:null});
  expect(g.workspace.decisionStatus('reports').current?.disposition).toBe('defer');
  const r=fixture(),receipt=r.prepare(),activation=r.registry({operation:'activate',requestId:'activate',adoptionId:receipt.id,scopeDigest:receipt.scopeDigest,candidateDigest:receipt.candidateDigest,revision:1});r.workspace.linkActivation('reports',activation,[activation]);unlinkSync(join(r.archiveRoot,'manifests',activation));
  expect(r.workspace.inspect(Date.now()).comparisons[0]).toMatchObject({state:'deferred'});
});
it('freezes real case nominations, requires independent labels and keeps exposure pure until explicitly reserved',()=>{
  const f=fixture(),options={caseName:'daily',detectorId:'coverage_gap',split:'calibration' as const,maxUnflagged:0,unflagged:[],exposure:{id:'fixture-policy',minimumResolved:1,minimumLowerBound:0,attentionRemaining:1,expiresAt:Date.now()+86400000}};
  const preview=previewLearningTrust(f.directory,options);expect(preview).toMatchObject({nominationCount:1,independentIncidentCount:1,labelsCreated:0});
  expect(()=>configureLearningTrust(f.directory,options,[])).toThrow(/authority/);configureLearningTrust(f.directory,options,[preview.policyDigest]);
  expect(f.workspace.trust().previewExposure(Date.now())).toMatchObject({mode:'silent',reason:'insufficient-independent-evidence'});
  const label=previewLearningCaseLabel(f.directory,f.comparison.caseReference!);f.workspace.trust().linkCaseOutcome(label.predictionId,f.comparison.caseReference!,[label.digest],'fixture-independent-human');
  const bytes=readFileSync(join(f.directory,'trust/events.jsonl'));f.workspace.inspect(Date.now());expect(readFileSync(join(f.directory,'trust/events.jsonl'))).toEqual(bytes);
  expect(f.workspace.trust().previewExposure(Date.now()).mode).toBe('ask');
  f.workspace.trust().expose('actual-question',Date.now());
  expect(openLearningWorkspace(f.directory).trust().previewExposure(Date.now()).mode).toBe('silent');
  expect(f.workspace.trust().inspect(Date.now()).attentionUsed).toBe(1);
  f.workspace.decideCase('daily',{caseManifestId:f.caseManifestId,priorDecisionId:f.decision.id,disposition:'expected_behavior',note:'Withdraw prior label'});
  expect(f.workspace.trust().inspect(Date.now()).calibration.reports[0].resolved).toBe(0);
});
it('uses actual v3 frozen inputs and exact selected snapshot identity',()=>{
  const f=fixture(),digest=sha('v3-obligation'),p=sha('v3-policy');
  const snapshot={snapshotDigest:f.config.scopeDigest,scopeValid:true,obligations:[{id:'checkpoint',digest,intentDigest:p,policyDigest:p,artifactDigest:p,acceptance:'unaccepted' as const,coverage:'available' as const}]};
  const facts={scopeDigest:f.config.scopeDigest,version:'fixture-v3',population:f.config.population,expectedWaits:[],checkpoints:[{obligationDigest:digest,deadlineMs:10,observedAt:11,status:'pending' as const,evidence:p}],violations:[],priorAccepted:[]};
  const observation=retainWorkSignalObservation(f.archiveRoot,snapshot,facts),batch=captureWorkSignalCases(f.archiveRoot,observation.manifestId);
  f.workspace.bindCases({name:'signals',title:'Actual frozen v3 inputs',version:3,batchId:batch.batchId});
  const page=f.workspace.cases('signals');expect(page.total).toBe(1);
  expect(f.workspace.caseEvidence('signals',page.items[0].caseManifestId)).toContainEqual(expect.objectContaining({manifestId:observation.manifestId,role:'frozen-inputs',status:'available'}));
  const preview=previewLearningTrust(f.directory,{caseName:'signals',detectorId:page.items[0].candidate.detector.id,split:'calibration',maxUnflagged:0,unflagged:[],exposure:null});
  expect(preview.independentIncidentCount).toBe(1);f.workspace.configureTrust(preview.input,[preview.policyDigest]);
  const other=retainWorkSignalObservation(f.archiveRoot,{...snapshot,snapshotDigest:sha('other-snapshot')},{...facts,scopeDigest:sha('other-snapshot')}),foreign=captureWorkSignalCases(f.archiveRoot,other.manifestId);
  expect(()=>f.workspace.bindCases({name:'foreign',title:'Wrong snapshot',version:3,batchId:foreign.batchId})).toThrow(/snapshot/);
});
it('refuses scope/population rebinding and copied stores instead of resetting choices or attention',()=>{
  const f=fixture();expect(()=>createLearningWorkspace(f.directory,{...f.config,scopeDigest:sha('different')})).toThrow(/bound/);
  expect(f.workspace.dashboardBinding()).toEqual({trustDirectory:null,trustPolicyId:null});
  expect(f.workspace.preparedAdoption('reports')).toBeNull();
  expect(()=>f.workspace.bindComparison({...f.comparison,name:'bad',adoptionBinding:{...f.adoptionBinding,scopeDigest:sha('different')}})).toThrow(/scope|binding/);
  const copy=join(f.root,'copy');mkdirSync(copy,{mode:0o700});cpSync(f.directory,copy,{recursive:true});expect(()=>openLearningWorkspace(copy)).toThrow(/registration/);
});
