import { createHash } from 'node:crypto';
export const productSha=(s:string)=>createHash('sha256').update(s).digest('hex');
export function productFixture(root:string){
 const models=['gpt-5.4','gpt-5.6-sol','gpt-5.5','gpt-5.3-codex-spark','gpt-5.4-mini','gpt-5.6-luna'],sha=productSha,h=sha('fixed');
 const base:any={version:'codex-synthetic-charter-v1',provider:'openai-codex',destination:'https://chatgpt.com/backend-api/codex/responses',rolePolicy:models.map((model,k)=>({model,role:k===0?'proposer':k===1||k===5?'subject':'judge',canonical:'fixture-'+k,lineage:'shared-fixture'})),identityEvidence:{kind:'fixture',reference:'synthetic only'},hostEvidence:{kind:'fixture',reference:'no network/home'},accountId:'fixture-account',serverOutputTokenCap:null,runtime:{sdkRoot:'/sdk',oauthFile:'/no-auth',fingerprints:{}},limits:{calls:5,requestBytes:4096,responseBytes:16384,totalRequestBytes:20480,totalResponseBytes:81920,callMs:10000,wallMs:150000},invocations:models.slice(0,5).map((model,k)=>({id:['proposer','subject','first','second','tie'][k],model,role:k===0?'proposer':k===1?'subject':'judge',effort:'low',instructions:'Frozen fixture',input:'Return4',expectedSha256:sha('4'),subjectId:k<2?null:'subject'}))};
 const material={a:{skill:'Skill A: return4',prompt:'Prompt A',configuration:'{}'},b:{skill:'Skill B: return4',prompt:'Prompt B',configuration:'{}'}};
 const roles={proposer:{requested:models[0],canonical:'fixture-0'},judges:models.slice(2,5).map((requested,k)=>({requested,canonical:'fixture-'+(k+2)})),subjects:{a:{requested:models[1],canonical:'fixture-1',effort:'low'},b:{requested:models[5],canonical:'fixture-5',effort:'medium'}}};
 const product={kind:'producer-product-v1',base,protocol:{kind:'producer-ipc-v1',author:'fixture-author',archiveRoot:root+'/archive',scope:{station:'build',taskClass:'synthetic',risk:'tiny',population:'fixture',version:h},catalogue:models.map((requested,k)=>({requested,canonical:'fixture-'+k,lineage:'shared-fixture',efforts:['low','medium']})),roles,draft:{family:'intervention',investigationSha256:h,resourceMetric:'tool_calls',axes:['model','effort','skill','prompt'],common:{mode:'force',scenarioSha256:h,rubricSha256:h,fixtureSha256:h,heldoutSha256:h,harnessSha256:h,judgePolicySha256:h},proposer:models[0],judge:models[2],cases:[{id:'boundary',criteria:1,reps:2,threshold:1,critical:false},{id:'heldout',criteria:1,reps:1,threshold:1,critical:true}],arms:Object.entries(material).map(([id,m])=>({id,configuration:{model:(roles.subjects as any)[id].requested,effort:(roles.subjects as any)[id].effort,skill:sha(m.skill),prompt:sha(m.prompt),configuration:sha(m.configuration)}}))},expected:{a:[sha('4'),sha('4'),sha('4')],b:[sha('4'),sha('4'),sha('4')]}},material,cases:{boundary:{input:'Return4',criterion:'Exactly4',partition:'calibration',boundary:true},heldout:{input:'Return4 again',criterion:'Exactly4',partition:'heldout',boundary:false}},reference:{kind:'synthetic',digest:h,labels:{boundary:'PASS',heldout:'PASS'}},retro:null,limits:{calls:24,totalRequestBytes:98304,totalResponseBytes:393216}} as any;
 const entries=Object.entries(product.cases).sort() as [string,any][];
 product.protocol.draft.common.scenarioSha256=sha(JSON.stringify(entries.map(([id,c])=>[id,c.input])));product.protocol.draft.common.rubricSha256=sha(JSON.stringify(entries.map(([id,c])=>[id,c.criterion])));product.protocol.draft.common.heldoutSha256=sha(JSON.stringify(product.protocol.draft.cases.map((c:any)=>[c.id,c.reps,product.cases[c.id].partition,product.cases[c.id].boundary])));
 return product;
}
